branches:
  only:
    - master

os: windows

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

before_install:
  - npm install windows-build-tools --global --production
install:
  - npm install
script:
  - npm run document
  - cd ${FOLDER}
  - git init
  - git config user.name ${UID}
  - git config user.email ${EMAIL}
  - git add .
  - git commit -m "${MESSAGE}"
  - git push --force --quiet https://${TOKEN}@${GIT_URI}.git master:${BRANCH}
